name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
          perf
          ci
          build
        requireScope: false
        subjectPattern: ^[A-Z].+[^.]$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          starts with an uppercase letter and doesn't end with a period.
          
    - name: Check PR description
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          if (!pullRequest.body || pullRequest.body.length < 10) {
            core.setFailed('PR description is too short. Please provide a meaningful description.');
          }
          
    - name: Check file size
      run: |
        find . -type f -size +1M -not -path "./.git/*" -not -path "./app/build/*" | head -10 > large_files.txt
        if [ -s large_files.txt ]; then
          echo "Large files detected:"
          cat large_files.txt
          exit 1
        fi
        
    - name: Check for sensitive files
      run: |
        sensitive_patterns=(
          "*.pem"
          "*.key"
          "*.p12"
          "*.jks"
          "local.properties"
          "google-services.json"
          "keystore.properties"
        )
        
        for pattern in "${sensitive_patterns[@]}"; do
          if find . -name "$pattern" -not -path "./.git/*" | grep -q .; then
            echo "Warning: Sensitive file pattern found: $pattern"
          fi
        done
